FROM  ws-typescript-development-webpack



RUN mkdir -p /app/dist \
  && mkdir -p /app/dist-build \
  && mkdir -p /app/tools \
  && mkdir -p /app/resources \
  && mkdir -p /app/node_modules \
  && mkdir -p /app/src

COPY dist-build /app/dist-build
COPY .angular-cli.json /app/.angular-cli.json
COPY karma.conf.js /app/karma.conf.js
COPY protractor.conf.js /app/protractor.conf.js
COPY tslint.json /app/tslint.json
COPY package.json /app/package.json
COPY tsconfig.json /app/tsconfig.json
COPY src /app/src

WORKDIR /app

RUN chmod -R 777 /app/dist-build

RUN npm install

EXPOSE 4200

CMD ["npm",  "start"]
#ENTRYPOINT ["/bin/sh", "-c", "while true; do sleep 1; done"]