version: '3'

services:

  ws-frontend-product:
    restart: always
    image: local-ws-frontend-product-webpack:latest
    container_name: local-ws-frontend-product
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    command: ['npm', 'run', 'start']
    volumes:
      - ./.angular-cli.json:/app/.angular-cli.json:rw
      - ./karma.conf.js:/app/karma.conf.js:rw
      - ./protractor.conf.js:/protractor/karma.conf.js:rw
      - ./tslint.json:/app/tslint.json:rw
      - ./package.json:/app/package.json:rw
      - ./package-lock.json:/app/package-lock.json:rw
      - ./tsconfig.json:/app/tsconfig.json
      - ./src:/app/src
    ports:
      - '4200:4200'

